# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authentication_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61uthentication_service.proto\x12\x0e\x61uthentication\"X\n\x0cLoginRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x10\n\x08group_id\x18\x04 \x01(\t\"\x1c\n\nLoginReply\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32Q\n\x05Login\x12H\n\nLoginCheck\x12\x1c.authentication.LoginRequest\x1a\x1a.authentication.LoginReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authentication_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=48
  _globals['_LOGINREQUEST']._serialized_end=136
  _globals['_LOGINREPLY']._serialized_start=138
  _globals['_LOGINREPLY']._serialized_end=166
  _globals['_LOGIN']._serialized_start=168
  _globals['_LOGIN']._serialized_end=249
# @@protoc_insertion_point(module_scope)
