# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jnx_common_base_types.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bjnx_common_base_types.proto\x12\x0ejnx.jet.common\x1a google/protobuf/descriptor.proto\"0\n\x07TimeVal\x12\x0f\n\x07seconds\x18\x01 \x01(\x04\x12\x14\n\x0cmicroseconds\x18\x02 \x01(\x04\"F\n\tRpcStatus\x12(\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1a.jnx.jet.common.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x0cNumericRange\x12\x0b\n\x03min\x18\x01 \x01(\r\x12\x0b\n\x03max\x18\x02 \x01(\r\"D\n\x10NumericRangeList\x12\x30\n\nrange_list\x18\x01 \x03(\x0b\x32\x1c.jnx.jet.common.NumericRange*&\n\nStatusCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01:4\n\x0cjapi_version\x12\x1c.google.protobuf.FileOptions\x18\xd0\x86\x03 \x01(\t:5\n\rjunos_release\x12\x1c.google.protobuf.FileOptions\x18\xd1\x86\x03 \x01(\tB\x11\x82\xb5\x18\x05\x30.1.0\x8a\xb5\x18\x04\x31\x38.4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jnx_common_base_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\202\265\030\0050.1.0\212\265\030\00418.4'
  _globals['_STATUSCODE']._serialized_start=315
  _globals['_STATUSCODE']._serialized_end=353
  _globals['_TIMEVAL']._serialized_start=81
  _globals['_TIMEVAL']._serialized_end=129
  _globals['_RPCSTATUS']._serialized_start=131
  _globals['_RPCSTATUS']._serialized_end=201
  _globals['_NUMERICRANGE']._serialized_start=203
  _globals['_NUMERICRANGE']._serialized_end=243
  _globals['_NUMERICRANGELIST']._serialized_start=245
  _globals['_NUMERICRANGELIST']._serialized_end=313
# @@protoc_insertion_point(module_scope)
