# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jnx_common_addr_types.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import jnx_common_base_types_pb2 as jnx__common__base__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bjnx_common_addr_types.proto\x12\x0ejnx.jet.common\x1a\x1bjnx_common_base_types.proto\"G\n\tIpAddress\x12\x15\n\x0b\x61\x64\x64r_string\x18\x01 \x01(\tH\x00\x12\x14\n\naddr_bytes\x18\x02 \x01(\x0cH\x00\x42\r\n\x0b\x61\x64\x64r_format\"H\n\nMacAddress\x12\x15\n\x0b\x61\x64\x64r_string\x18\x01 \x01(\tH\x00\x12\x14\n\naddr_bytes\x18\x02 \x01(\x0cH\x00\x42\r\n\x0b\x61\x64\x64r_format\"e\n\tIpNetwork\x12\x1a\n\x10host_addr_string\x18\x01 \x01(\tH\x00\x12\x19\n\x0fhost_addr_bytes\x18\x02 \x01(\x0cH\x00\x12\x12\n\nprefix_len\x18\x03 \x01(\rB\r\n\x0b\x61\x64\x64r_format\"\x95\x01\n\x10IpFragementFlags\x12\x11\n\tnot_match\x18\x01 \x01(\x08\x12\r\n\x05match\x18\x02 \x01(\x08\x12\x16\n\x0e\x64ont_fragement\x18\x03 \x01(\x08\x12\x16\n\x0eis_a_fragement\x18\x04 \x01(\x08\x12\x17\n\x0f\x66irst_fragement\x18\x05 \x01(\x08\x12\x16\n\x0elast_fragement\x18\x06 \x01(\x08\"Y\n\x11\x42ypassOrTerminate\x12\x19\n\x0f\x62ypass_loopback\x18\x01 \x01(\x08H\x00\x12\x1a\n\x10tunnel_terminate\x18\x02 \x01(\x08H\x00\x42\r\n\x0btunnel_type*6\n\rAddressFormat\x12\x12\n\x0e\x41\x44\x44RESS_STRING\x10\x00\x12\x11\n\rADDRESS_BYTES\x10\x01*\\\n\x06\x41\x66Type\x12\x12\n\x0e\x41\x46_UNSPECIFIED\x10\x00\x12\x0b\n\x07\x41\x46_INET\x10\x01\x12\x0c\n\x08\x41\x46_INET6\x10\x02\x12\n\n\x06\x41\x46_MAC\x10\x03\x12\x0b\n\x07\x41\x46_MPLS\x10\x04\x12\n\n\x06\x41\x46_ISO\x10\x05*\x90\x01\n\x08TcpFlags\x12\x14\n\x10TCP_FLAG_INVALID\x10\x00\x12\x10\n\x0cTCP_FLAG_FIN\x10\x01\x12\x10\n\x0cTCP_FLAG_SYN\x10\x02\x12\x10\n\x0cTCP_FLAG_RST\x10\x04\x12\x11\n\rTCP_FLAG_PUSH\x10\x08\x12\x10\n\x0cTCP_FLAG_ACK\x10\x10\x12\x13\n\x0fTCP_FLAG_URGENT\x10 B\x11\x82\xb5\x18\x05\x30.2.0\x8a\xb5\x18\x04\x31\x39.4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jnx_common_addr_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\202\265\030\0050.2.0\212\265\030\00419.4'
  _globals['_ADDRESSFORMAT']._serialized_start=569
  _globals['_ADDRESSFORMAT']._serialized_end=623
  _globals['_AFTYPE']._serialized_start=625
  _globals['_AFTYPE']._serialized_end=717
  _globals['_TCPFLAGS']._serialized_start=720
  _globals['_TCPFLAGS']._serialized_end=864
  _globals['_IPADDRESS']._serialized_start=76
  _globals['_IPADDRESS']._serialized_end=147
  _globals['_MACADDRESS']._serialized_start=149
  _globals['_MACADDRESS']._serialized_end=221
  _globals['_IPNETWORK']._serialized_start=223
  _globals['_IPNETWORK']._serialized_end=324
  _globals['_IPFRAGEMENTFLAGS']._serialized_start=327
  _globals['_IPFRAGEMENTFLAGS']._serialized_end=476
  _globals['_BYPASSORTERMINATE']._serialized_start=478
  _globals['_BYPASSORTERMINATE']._serialized_end=567
# @@protoc_insertion_point(module_scope)
