# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import management_service_pb2 as management__service__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in management_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ManagementRpcApiStub(object):
    """
    MGD Service Definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteOpCommand = channel.unary_stream(
                '/management.ManagementRpcApi/ExecuteOpCommand',
                request_serializer=management__service__pb2.ExecuteOpCommandRequest.SerializeToString,
                response_deserializer=management__service__pb2.ExecuteOpCommandResponse.FromString,
                _registered_method=True)
        self.ExecuteCfgCommand = channel.unary_unary(
                '/management.ManagementRpcApi/ExecuteCfgCommand',
                request_serializer=management__service__pb2.ExecuteCfgCommandRequest.SerializeToString,
                response_deserializer=management__service__pb2.ExecuteCfgCommandResponse.FromString,
                _registered_method=True)
        self.GetEphemeralConfig = channel.unary_unary(
                '/management.ManagementRpcApi/GetEphemeralConfig',
                request_serializer=management__service__pb2.GetEphemeralConfigRequest.SerializeToString,
                response_deserializer=management__service__pb2.GetEphemeralConfigResponse.FromString,
                _registered_method=True)
        self.EditEphemeralConfig = channel.unary_unary(
                '/management.ManagementRpcApi/EditEphemeralConfig',
                request_serializer=management__service__pb2.EditEphemeralConfigRequest.SerializeToString,
                response_deserializer=management__service__pb2.EditEphemeralConfigResponse.FromString,
                _registered_method=True)


class ManagementRpcApiServicer(object):
    """
    MGD Service Definitions
    """

    def ExecuteOpCommand(self, request, context):
        """
        It executes the operational command specified in
        ExecuteOpCommandRequest. This is a streaming api
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCfgCommand(self, request, context):
        """
        The RPC will enable user to load and commit configuration on a junos
        device
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEphemeralConfig(self, request, context):
        """
        This RPC will return the configuration in the ephemeral database
        for Path specified in the request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditEphemeralConfig(self, request, context):
        """
        This RPC will perfom load-configuration and commit in JUNOS in ephemeral
        database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagementRpcApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteOpCommand': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteOpCommand,
                    request_deserializer=management__service__pb2.ExecuteOpCommandRequest.FromString,
                    response_serializer=management__service__pb2.ExecuteOpCommandResponse.SerializeToString,
            ),
            'ExecuteCfgCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCfgCommand,
                    request_deserializer=management__service__pb2.ExecuteCfgCommandRequest.FromString,
                    response_serializer=management__service__pb2.ExecuteCfgCommandResponse.SerializeToString,
            ),
            'GetEphemeralConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEphemeralConfig,
                    request_deserializer=management__service__pb2.GetEphemeralConfigRequest.FromString,
                    response_serializer=management__service__pb2.GetEphemeralConfigResponse.SerializeToString,
            ),
            'EditEphemeralConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.EditEphemeralConfig,
                    request_deserializer=management__service__pb2.EditEphemeralConfigRequest.FromString,
                    response_serializer=management__service__pb2.EditEphemeralConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'management.ManagementRpcApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('management.ManagementRpcApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManagementRpcApi(object):
    """
    MGD Service Definitions
    """

    @staticmethod
    def ExecuteOpCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/management.ManagementRpcApi/ExecuteOpCommand',
            management__service__pb2.ExecuteOpCommandRequest.SerializeToString,
            management__service__pb2.ExecuteOpCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCfgCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementRpcApi/ExecuteCfgCommand',
            management__service__pb2.ExecuteCfgCommandRequest.SerializeToString,
            management__service__pb2.ExecuteCfgCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEphemeralConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementRpcApi/GetEphemeralConfig',
            management__service__pb2.GetEphemeralConfigRequest.SerializeToString,
            management__service__pb2.GetEphemeralConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditEphemeralConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementRpcApi/EditEphemeralConfig',
            management__service__pb2.EditEphemeralConfigRequest.SerializeToString,
            management__service__pb2.EditEphemeralConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
